config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items do
    member do
      patch :complete
    end
  end
  

end

app/models/item.rb
class Item < ActiveRecord::Base
    
    def completed?
        !completed_at.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
    before_action :find_item, only: [:show, :edit, :destroy, :update, :complete]
    
    def index
        @items = Item.all.order("created_at DESC")
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(param_items)
            
        if @item.save
            redirect_to items_path
        else
            render "new"
        end
    end
    
    def show
      
    end
    
    def edit
       
    end
    
    def destroy
      
        if @item.destroy
            redirect_to root_path
        else
            render 'index'
        end
        
    end
    
    def complete
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
    end
    
    
    def update
        
        
        if @item.update_attributes(param_items)
            redirect_to item_path(@item)
        else 
            render "edit"
        end
    
    end
    
    def find_item
         @item = Item.find(params[:id])
    end
    
    def param_items
        params.require(:item).permit(:title, :description)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "Aufgabe" %>
    <%= f.input :description, label: "Beschreibung" %>
    <%= f.button :submit, "Eintrag" %>
<% end %>

app/views/items/index.html.erb
<h1>Meine Aufgaben</h1>
<%=button_to "Neue Aufgabe", new_item_path, method: :get, class: "btn btn-default"%>
<hr>
<% @items.each do |item| %>
<div class = "row item">

<% if item.completed? %>
<div class = "col-md-6">
<h3><s><%= link_to item.title, item_path(item.id)  %></s></h3>
<p><s><%= item.description %></s></p>
<p><%= time_ago_in_words(item.completed_at) %> ago.</p>
</div>
<div class = "col-md-2">
    
</div>

<% else %>

<div class = "col-md-6">
<h3><%= link_to item.title, item_path(item.id)  %></h3>
<p><%= item.description %></p>
</div>
<div class = "col-md-2">
    <%= link_to complete_item_path(item), method: :patch do %>
     
<h3><i class="fa fa-check" aria-hidden="true"></i></h3>
<% end %>
</div>

<% end %>

</div>
<hr>
<% end %>

app/views/items/new.html.erb
<h1>Neue Aufgabe anlegen</h1>


<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Aufgabe" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit, "Eintrag" %>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<p><%= @item.description %></p>
<p>
    <%= link_to items_path do %>
    <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
    <% end %>
    
    <%= link_to edit_item_path do %> 
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
    <% end %>

    <%= link_to item_path(@item),:data => {:confirm => "Sicher?"} ,:method => :delete do %>
    <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  <!-- link_to "Löschen2", item_path(@item), data: {confirm: "Bist du sicher?"}, method: :delete  -->
</p>

<!-- button_to "Zurück", root_path, method: :get, class: "btn btn-default" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aufgaben</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.fontawesome.com/d333a4594d.js"></script>

</head>
<body>
<div class = "container">
<%= yield %>
</div>
</body>
</html>